# -*- coding: utf-8 -*-
"""c17_test(variant1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNMvE_0_bFjDLQ26sGirBp1xPVDVVAC8
"""

!apt-get -qq update
!apt-get -qq install -y yosys

!which yosys-abc

from google.colab import files
uploaded = files.upload()

!mv "c17 (2).bench" c17.bench

!yosys-abc -c "read_bench c17.bench; strash; print_stats"

!yosys-abc -c "read_bench c17.bench; strash; balance; rewrite; refactor; strash; write_bench -l c17_variant.bench"

!yosys-abc -c "cec c17.bench c17_variant.bench"

from google.colab import files
files.download("c17_variant.bench")