# -*- coding: utf-8 -*-
"""c17ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNolIz-_nMvk9_I6CAAXtEZMyxuyASBT
"""

!apt-get -qq update
!apt-get -qq install -y yosys
!which yosys-abc

from google.colab import files
uploaded = files.upload()

!mv "c17 (2) (1).bench" c17.bench
!rm -f "c17 (2).bench"
!ls -la

!yosys-abc -c "read_bench c17.bench; strash; print_stats"

!yosys-abc -c "read_bench c17.bench; strash; balance; rewrite; print_stats; write_bench -l c17_v1.bench"

!yosys-abc -c "cec c17.bench c17_v1.bench"

!yosys-abc -c "read_bench c17.bench; strash; refactor -z; print_stats; write_bench -l c17_v2.bench"

!diff c17.bench c17_v2.bench

!yosys-abc -c "cec c17.bench c17_v2.bench"

!yosys-abc -c "read_bench c17.bench; strash; refactor -z; strash; print_stats; write_bench -l c17_v2_aig.bench"
!cat c17_v2_aig.bench