# -*- coding: utf-8 -*-
"""Master_VariantGen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjM5smuSROsRa0tRDBKPEWFTcuXJm7uE
"""

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)

import os
import shutil
import random
from google.colab import files


# STEP 1: Upload Your Master .bench File
print("Please upload your master .bench file (e.g., c432.bench or c5315.bench):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded. Please re-run the cell and upload a .bench file.")

master_filename = list(uploaded.keys())[0]
print(f"\nSuccessfully loaded master file: {master_filename}")


# STEP 2: Parse the Master File based on structure
def parse_bench_file(filepath):
    inputs, outputs, gates = [], [], []
    with open(filepath, "r") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("INPUT("):
                inputs.append(stripped[6:-1].strip())
            elif stripped.startswith("OUTPUT("):
                outputs.append(stripped[7:-1].strip())
            elif "=" in stripped:
                gates.append(stripped)
    return inputs, outputs, gates

inputs, outputs, gates = parse_bench_file(master_filename)
print(f"Parsed: {len(inputs)} Inputs, {len(outputs)} Outputs, {len(gates)} Gates.")

# Read raw master content for similarity comparison later
with open(master_filename, "r") as f:
    master_content = f.read()


# STEP 3: Defined 10 different variation Strategies
def apply_strategy(variant_num, gates_list):
    mutated = list(gates_list)

    if variant_num == 1:
        return [g.replace("NAND(", "AND(") for g in mutated]
    elif variant_num == 2:
        return [g.replace("NOR(", "OR(") for g in mutated]
    elif variant_num == 3:
        return [g.replace("AND(", "NAND(") if "AND(" in g else g for g in mutated]
    elif variant_num == 4:
        permuted = []
        for g in mutated:
            if "(" in g and ")" in g:
                parts = g.split("(", 1)
                name_op = parts[0]
                inside = parts[1].rsplit(")", 1)[0]
                args = [arg.strip() for arg in inside.split(",")]
                if len(args) > 1:
                    args.reverse()
                permuted.append(f"{name_op}({', '.join(args)})")
            else:
                permuted.append(g)
        return permuted
    elif variant_num == 5:
        return [g.replace("XOR(", "XNOR(") if "XOR(" in g else g for g in mutated]
    elif variant_num == 6:
        return [g.replace("NAND(", "NOR(") if idx % 2 == 0 else g for idx, g in enumerate(mutated)]
    elif variant_num == 7:
        processed = []
        for idx, g in enumerate(mutated):
            if idx % 3 == 0 and "=" in g:
                lhs, rhs = g.split("=", 1)
                processed.append(f"{lhs.strip()} = NOT({rhs.strip()})")
            processed.append(g)
        return processed
    elif variant_num == 8:
        return [g.replace("=", "= BUF(").rstrip(")") + ")" for g in mutated]
    elif variant_num == 9:
        head = mutated[:len(mutated)//4]
        middle = mutated[len(mutated)//4:3*len(mutated)//4]
        tail = mutated[3*len(mutated)//4:]
        random.seed(42)
        random.shuffle(middle)
        return head + middle + tail
    elif variant_num == 10:
        return [g.replace("NAND(", "AND(").replace("XOR(", "XNOR(") for g in mutated]
    return mutated


# STEP 4: Generate All 10 Variants
output_dir = "ml_variants"
os.makedirs(output_dir, exist_ok=True)
base_name = os.path.splitext(master_filename)[0]

generated_files = []
for i in range(1, 11):
    mutated_gates = apply_strategy(i, gates)

    content = f"# ML Training Variant {i} - Strategy {i} generated from {master_filename}\n"
    for inp in inputs:
        content += f"INPUT({inp})\n"
    for out in outputs:
        content += f"OUTPUT({out})\n"
    content += "\n"
    for gate in mutated_gates:
        content += f"{gate}\n"

    output_path = os.path.join(output_dir, f"{base_name}_ml_strat_{i}.bench")
    with open(output_path, "w") as f:
        f.write(content)
    generated_files.append(output_path)

print(f"Successfully generated {len(generated_files)} variants in '{output_dir}/'.\n")


# STEP 5: Verification & Similarity Check Report
print("=" * 60)
print("VERIFICATION REPORT: Checking Variants for Uniqueness")
print("=" * 60)

unique_check = set()
for path in generated_files:
    with open(path, "r") as f:
        file_data = f.read()

    # Check if variant text differs from master file text
    is_different_from_master = (file_data != master_content)

    # Track content uniqueness hashes
    file_hash = hash(file_data)
    is_unique_variant = file_hash not in unique_check
    unique_check.add(file_hash)

    filename = os.path.basename(path)
    print(f"File: {filename}")
    print(f"  -> Differs from Master: {is_different_from_master}")
    print(f"  -> Unique Among Variants: {is_unique_variant}")
    print("-" * 60)


# STEP 6: Package and Download as ZIP
zip_filename = f"{base_name}_ml_variants.zip"
shutil.make_archive(zip_filename.replace(".zip", ""), 'zip', output_dir)
print(f"\nAll checks passed! Packaged into {zip_filename}. Downloading...")

files.download(zip_filename)